controllers:
  joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: "yaw_joint"
    pid: { p: 20, i: 0, d: 0.82, i_clamp_max: 0.3, i_clamp_min: -0.3, antiwindup: true, publish_state: true }