controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500
  gimbal_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ pitch_joint_motor ]
    velocity:
      joint: pitch_joint
      search_velocity: 6.28
      vel_threshold: 1e-2
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
  joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: "yaw_joint"
    pid: { p: 16, i: 10, d: 0.1, i_clamp_max: 0.4, i_clamp_min: -0.4, antiwindup: true, publish_state: true }
